# version: '3.8'

services:
  backend:
    build: .
    #   context: .
    #   dockerfile: Dockerfile
    # container_name: rag_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./vectorstore:/app/vectorstore
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  frontend:
    build: .
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend